import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Jeep Tour",
  description: "Generated by alphabytein co.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light"> {/* ✅ kunci light mode */}
      <body className="bg-white text-black">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

