import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import FloatingWhatsapp from "./components/FloatingWhatsapp";

export const metadata = {
  title: "Jeep Tour",
  description: "Generated by alphabytein co.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light"> {/* ✅ kunci light mode */}
      <body className="bg-white text-black min-h-screen flex flex-col">
        
        {/* Navbar tetap di atas */}
        <Navbar />

        {/* Konten utama mendorong footer ke bawah */}
        <main className="flex-grow">
          {children}
        </main>

        {/* Footer selalu di bawah */}
        <Footer />

        <FloatingWhatsapp />

      </body>
    </html>
  );
}
